/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BroadcastClient {
  constructor()
  sendCameraSwitchPosition(position: number, group: number, camera: number): void
  sendCameraSwitchNumber(carNumber: string, group: number, camera: number): void
  setCameraState(cameraState: number): void
  setReplayPlaySpeed(speed: number, slowMotion: boolean): void
  setReplayPlayPosition(mode: ReplayPositionMode, frameNumber: number): void
  searchReplay(mode: ReplaySearchMode): void
  toggleReplayState(): void
  reloadAllTextures(): void
  reloadTextures(carIndex: number): void
  sendChatCommand(mode: ChatCommandMode): void
  sendChatMacro(macroNumber: number): void
  sendPitCommand(mode: PitCommandMode, value?: number | undefined | null): void
  sendTelemetryCommand(mode: TelemetryCommandMode): void
  sendForceFeedbackCommand(value: number): void
  searchReplaySessionTime(sessionNumber: number, sessionTimeMs: number): void
  controlVideoCapture(mode: VideoCaptureMode): void
}

export declare const enum ChatCommandMode {
  Macro = 0,
  Begin = 1,
  Reply = 2,
  Cancel = 3
}

export declare const enum PitCommandMode {
  Clear = 0,
  Tearoff = 1,
  Fuel = 2,
  Lf = 3,
  Rf = 4,
  Lr = 5,
  Rr = 6,
  ClearTires = 7,
  FastRepair = 8,
  ClearTearoff = 9,
  ClearFastRepair = 10,
  ClearFuel = 11
}

export declare const enum ReplayPositionMode {
  Begin = 0,
  Current = 1,
  End = 2
}

export declare const enum ReplaySearchMode {
  ToStart = 0,
  ToEnd = 1,
  PreviousSession = 2,
  NextSession = 3,
  PreviousLap = 4,
  NextLap = 5,
  PreviousFrame = 6,
  NextFrame = 7,
  PreviousIncident = 8,
  NextIncident = 9
}

export declare const enum TelemetryCommandMode {
  Stop = 0,
  Start = 1,
  Restart = 2
}

export declare const enum VideoCaptureMode {
  ScreenShot = 0,
  StartCapture = 1,
  EndCapture = 2,
  ToggleCapture = 3,
  ShowTimer = 4,
  HideTimer = 5
}
